### ISSUE TITLE
ReferenceError: aliasURL is not defined

### ISSUE THREAD

**Issue by moe93** [Fmstrat/lpp#11]
```
lpp  |
lpp  | > lemmy-post-purger@1.0.0 start
lpp  | > node index.js
lpp  |
lpp  | (node:22) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
lpp  | (Use `node --trace-deprecation ...` to show where the warning was created)
lpp  | Purging 0 posts older than 7 days
lpp  | Purging images older than 7 days
lpp  | Processing 414 posts with thumbnails
lpp  | /app/pictrs.js:168
lpp  |         console.error(`Failed on ${aliasUrl}`)
lpp  |                                    ^
lpp  |
lpp  | ReferenceError: aliasUrl is not defined
lpp  |     at purgePictrs (/app/pictrs.js:168:36)
lpp  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lpp  |     at async main (/app/index.js:146:7)
lpp  |
lpp  | Node.js v21.1.0
lpp exited with code 0
```

**Comment by Fmstrat** [comment]
Fixed https://github.com/Fmstrat/lpp/commit/59d7fb73ad843d6a129c70cd55bc987d4de1cea3
