### ISSUE TITLE
lpp crashes with db error 'error: relation "post" does not exist'

### ISSUE THREAD

**Issue by RogerSik** [Fmstrat/lpp#3]
Running Lemmy 0.18.4

```
k logs -f deploy/lpp

> lemmy-post-purger@1.0.0 start
> node index.js

/app/node_modules/pg-protocol/dist/parser.js:287
        const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                 ^

error: relation "post" does not exist
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:512:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 103,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '25',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1392',
  routine: 'parserOpenTable'
}

Node.js v19.5.0
npm notice 
npm notice New minor version of npm available! 9.3.1 -> 9.8.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.1>
npm notice Run `npm install -g npm@9.8.1` to update!
npm notice 
```

**Comment by Fmstrat** [comment]
Do you have anything custom set up in your DB? I see two potential reasons for this:
1. You have a unique DB name from default. If this is the case, the latest PR under testing (https://github.com/Fmstrat/lpp/pull/2) may help.
2. Your default schema is not `public`. This would be very odd on Lemmy, but I could see it occurring in a really custom setup.

**Comment by RogerSik** [comment]
Hmm,

i configurated nothing special at the DB:

*helm.yml*
```yml
  values:
    auth:
      # postgres (root) user
      postgresPassword: xxx
```

But because of time and the increasing space (even with cleanup i suppose) i currently shutdown my lemmy instance.
